### ISSUE TITLE
ELF32  vs  ELF64

### ISSUE THREAD

**Issue by loogycheung** [binance-exchange/binacpp#12]
Sir, my computer has W7 (32bit) and ubuntu 12.04 (32bit).  But libcurl.a   .so and libwebsockets.a  .so documents you supplied is 64 bit. I cound not recompile them except others.  May I beg you to send me the 32 bit .a  and .so document ?  thank you very much!  email:  loogycheung@163.com

**Comment by tensaix2j** [comment]
I think you can get it form their websites. Or go to their github, clone the source and compile.
 
libcurl is on https://github.com/curl/curl
libwebsocket is on https://github.com/warmcat/libwebsockets

**Comment by loogycheung** [comment]
haha, you know what, I just use a new 64 bit computer with only linux. All the makefile are recompile successfully. Thank you for sharing and replying question patiently.
One more doubts, the makefile in EXAMPLE, there is target: (   % :%.cpp  ), Terminal shows :( no target). So I change to:(      example :example.cpp        example_klines :example_klines.cpp     ).  Am I right ?

**Comment by tensaix2j** [comment]
instead of that, you can just
