### ISSUE TITLE
Issue: Example: make example

### ISSUE THREAD

**Issue by EArminjon** [binance-exchange/binacpp#30]
Hello,

I try to compile your library on your example directory. So i just deleted the binary example and run :
$> make example
I received an error :
-----------------------------
/usr/bin/ld: warning: librtmp.so.0, needed by ../lib/libcurl-7.56.0/lib/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libssl.so.1.0.0, needed by ../lib/libcurl-7.56.0/lib/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by ../lib/libcurl-7.56.0/lib/libcurl.so, not found (try using -rpath or -rpath-link)
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « SSL_CTX_set_verify@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « ASN1_STRING_type@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « CRYPTO_free@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « SSL_get_shutdown@OPENSSL_1.0.0 »
../lib/libwebsockets-2.4.0/lib/libwebsockets.so : référence indéfinie vers « SSL_want@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « SSL_get_verify_result@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « d2i_PKCS12_fp@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « UI_method_set_opener@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « EVP_cleanup@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « SSL_write@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « BIO_new@OPENSSL_1.0.0 »
../lib/libcurl-7.56.0/lib/libcurl.so : référence indéfinie vers « SSL_set_fd@OPENSSL_1.0.0 »
----------------------------

Can you help me ?

**Comment by kev6** [comment]
Your issue has already been answered in https://github.com/binance-exchange/binacpp/issues/27
