### ISSUE TITLE
-ljsoncpp not found

### ISSUE THREAD

**Issue by Micha1990** [binance-exchange/binacpp#8]
Hi, I downloaded the project and wanted to try the examples, but the terminal sais: /usr/bin/ld: cannot find -ljsoncpp. What can I do?

**Comment by tensaix2j** [comment]
try removing it and run make again.

**Comment by drvpn** [comment]
I am experiencing the same problems getting the example to compile (see paste of error below).  I see the previous suggestion was to "try removing it and run make again" what are you suggesting I remove?

Thanks!

/usr/bin/ld: cannot find -ljsoncpp
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'example' failed
make: *** [example] Error 1

**Comment by tensaix2j** [comment]
yes. Just remove the -ljsoncpp from the line and try again.

**Comment by tensaix2j** [comment]
well it wasn't there originally until someone added it , see the following commit
https://github.com/binance-exchange/binacpp/commit/71eaf491da18a733236a1f4d8e62e97909e0b324
