### ISSUE TITLE
Compile software

### ISSUE THREAD

**Issue by loogycheung** [binance-exchange/binacpp#9]
Dear Sir, I have lots of questions as new guys. 
Q1: I use"cmd->path->nmake" to make MAKEFILE compile with GUN Compiler， use VS2010 to compile .cpp and .h documents, am I right ? 
Q2: could you tell me which softwares to finish this project?   
May I send my question to your email for help. thank you very much!!

**Comment by tensaix2j** [comment]
1. Linux only.
2. Linux build essentials : eg:  g++

**Comment by loogycheung** [comment]
thank you ! haha
